---
- file:
    path: /etc/wireguard
    state: directory
    mode: 0755
- stat:
    path: /etc/wireguard/private-key
  register: wg_privkey
- stat:
    path: /etc/wireguard/public-key
  register: wg_pubkey
- name: generate private key
  shell: |
    wg genkey >/etc/wireguard/private-key
    chmod 0600 /etc/wireguard/private-key
  when: wg_privkey.stat.exists == False
- name: generate public key
  shell: |
    wg pubkey </etc/wireguard/private-key >/etc/wireguard/public-key
  when: wg_pubkey.stat.exists == False
