---
- name: add wireguard ppa
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: install wireguard dependencies
  apt:
    name:
      - linux-headers-virtual
      - resolvconf
    update_cache: yes

- name: install latest wireguard
  apt:
    name: wireguard
    state: latest
