---
- shell: echo {{ ansible_distribution }}

- include_tasks: install_debian.yml
  when: ansible_distribution == "Debian"

- include_tasks: install_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: install_fedora.yml
  when: ansible_distribution == "Fedora"

- name: load wireguard ko
  modprobe:
    name: wireguard

- include_tasks: configure.yml
