---
- shell: echo {{ ansible_distribution }}
- include_tasks: requirements_debian.yml
  when: ansible_distribution == "Debian"
- include_tasks: requirements_ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: requirements_fedora.yml
  when: ansible_distribution == "Fedora"
- include_tasks: build_and_install.yml
